version: '3.8'
services:
  node-app:
#    build: .
#    image: custom-react-app
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-react-app
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true